# Numpy : Introduction

**Numpy te permet de manipuler des données sous forme de tableau, ou array in english.**

**Réalise les missions ci-dessous avec Numpy.**

In [0]:
# Mission 1 : Afficher la version de Numpy
import numpy as np
import random
np.__version__

'1.16.5'

In [0]:
# Mission 2 : Créer un array Numpy de longueur 3, remplit de float qui valent 0.x, x pouvant prendre n'importe quel valeur
my_array = np.random.random_sample(3)
my_array

array([0.05949261, 0.82539101, 0.82445138])

In [0]:
# Mission 3 : Créer une fonction qui avec la méthode random.random() affichera 10 variables aléatoires strictement supérieur à 0.25

def my_randNos(value):
    new_nos = np.random.random_sample((value))
    print(new_nos + 0.25)

my_randNos(10)

[0.58363868 1.03049739 0.47310463 1.04639202 0.56189499 1.08528418
 0.76930017 0.6177868  1.24800344 0.44839806]


In [0]:
# Mission 4 : Que fait la méthode np.empty() ? Il ne faut pas juste recopier la doc, mais l'expliquer en français




La fonction empty () est utilisée pour créer un nouveau tableau de formes et de types donnés, sans initialiser les entrées.

In [0]:
# Mission 5 : Créer un array rempli de 7 zéros de type float
a = np.zeros(7)
a

array([0., 0., 0., 0., 0., 0., 0.])

In [0]:
# Mission 6 : Créer un array rempli de 10 chiffres aléatoires de type int
arr_new = np.random.randint(1, 10, 10)
arr_new

array([8, 7, 2, 4, 6, 3, 9, 6, 9, 6])

In [0]:
# Mission 7 : Créer un array qui contiendra 70 valeurs choisi aléatoirement parmi les nombres : 0, 1, 2, 3, 4, 5, 6, 7
arr_new1 = np.random.choice(np.array([0,1,2,3,4,5,6,7]), 70)

arr_new1

array([1, 2, 2, 3, 3, 7, 5, 6, 5, 5, 7, 1, 5, 4, 1, 3, 4, 0, 5, 6, 6, 4,
       3, 2, 5, 5, 2, 4, 3, 4, 1, 4, 0, 1, 7, 1, 7, 6, 7, 4, 1, 4, 5, 6,
       5, 7, 5, 4, 4, 2, 7, 1, 4, 2, 2, 6, 0, 7, 1, 5, 0, 1, 1, 6, 6, 4,
       0, 6, 5, 0])

In [0]:
# Mission 8 : Utilise l'opérateur de sciling pour accéder aux éléments entre la position 3 et 6 inclus de la mission 6

s_arr = arr_new[3:7]
s_arr

array([5, 6, 8, 9])

In [0]:
# Mission 9 : Utilise une méthode pour renvoyer l'index de l'élément minimum de l'array de la mission 7
arr_new2 = np.argmin(arr_new1) #argmin is to find the index of the lowest value
arr_new2

17

In [0]:
# Mission 10 : En utilisant une méthode numpy, renvoie les index des valeurs supérieurs à la valeur mediane de l'array de la mission 6
arr_median = np.median(arr_new)
arr_median



6.0

In [0]:
#result = np.where(arr_new > arr_median)

#result[0]

print(np.where(arr_new > arr_median))

(array([0, 1, 6, 8]),)


In [0]:
# Mission 11 : Après avoir créé 3 arrays remplie de int aléatoirement, que tu placeras dans un array
# Créer une fonction qui va parcourir tour à tour les éléments des 3 arrays.
# Cela donnera : Élément 1 de l'array 1, 2 et 3. Élement 2 de l'array 1, 2 et 3...

arr1 = np.random.randint(6, size = 4)
arr2 = np.random.randint(8,size =4)
arr3 = np.random.randint(10,size = 4)

print(arr1)
print(arr2)
print(arr3)

fin_arr = np.array([arr1, arr2, arr3])

def arr_funct1(fin_arr):
 
  for i in range(len(fin_arr)):
    #print(fin_arr[i][0])
    #print(fin_arr[i][1])
    #print(fin_arr[i][2])
    #print(fin_arr[i][3])
    for j in range(len(fin_arr[i])):
      print(fin_arr[i][j])
          
arr_funct1(fin_arr)
   
    

[1 3 3 3]
[3 1 5 1]
[0 7 3 0]
1
3
3
3
3
1
5
1
0
7
3
0


In [0]:
# Mission 12 : Créer un array et remplie le de 20 valeurs aléatoires de type float.
# Créer une fonction qui va parcourir le tableau et indiquer la valeur la plus petite et la plus grande du tableau.

arr_fl = np.random.rand(20)

def fun_Maxmini(arr_fl):
  
  print(np.min(arr_fl))
  print(np.max(arr_fl))
 
fun_Maxmini(arr_fl)

0.0440401061405612
0.9613768644878355


In [0]:
# Mission 13 : Créer 2 arrays, remplie les aléatoirement de 20 valeurs de type int compris entre 0 et 10.
# Créer une fonction qui va parcourir chaque array avec une boucle while.
# A chaque tour de boucle la fonction va comparer les valeurs des 2 arrays situé à la même position
# dans le but de renvoyer l'indice à laquelle les valeurs des 2 arrays sont égales.
# Si aucune valeur n'est égale à la même position dans les 2 arrays, renvoyer le message : .

arr1 = np.random.randint(0, 10, size = 20)
arr2 = np.random.randint(0, 10, size = 20)
print(arr1)
print(arr2)
def fun_loop(arr1, arr2):
  find = False
  i = 0
  while i <= 19:
    if arr1[i] == arr2[i]:
        find = True
        print(i)     
    i += 1
    
  if not find:
    print("Aucune valeur en commun")
    
fun_loop(arr1, arr2)

[5 6 0 2 9 4 8 5 6 2 8 5 0 0 6 8 0 4 9 6]
[7 7 0 0 3 0 1 6 1 1 8 8 5 4 6 9 9 7 5 4]
2
10
14
